### ISSUE TITLE
FidoMdsMetadataItemsProvider fails to parse metadata items

### ISSUE THREAD

**Issue by ChristophKaser** [webauthn4j/webauthn4j#412]
**Describe the bug**
When trying to access the Fido MDS metadata using FidoMdsMetadataItemsProvider with a valid token, the returned metadata is empty. This is caused by an exception in fetchMetadataStatement, which is ignored and written to the logger:

>16:39:18.448 [ForkJoinPool.commonPool-worker-1] WARN com.webauthn4j.metadata.FidoMdsMetadataItemsProvider - Failed to fetch MetadataTOCPayLoad
com.webauthn4j.converter.exception.DataConversionException: **Input data does not match expected form**
	at com.webauthn4j.converter.util.JsonConverter.readValue(JsonConverter.java:55)
	at com.webauthn4j.metadata.FidoMdsMetadataItemsProvider.fetchMetadataStatement(FidoMdsMetadataItemsProvider.java:248)
	at com.webauthn4j.metadata.FidoMdsMetadataItemsProvider.fetchFidoMdsMetadataItem(FidoMdsMetadataItemsProvider.java:209)
	at com.webauthn4j.metadata.FidoMdsMetadataItemsProvider.lambda$refresh$0(FidoMdsMetadataItemsProvider.java:165)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: **com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.webauthn4j.metadata.data.statement.AttachmentHints` (although at least one Creator exists): no default no-arguments constructor found**
 at [Source: (String)"<removed by me because of potential copyright issues>"]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1455)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1081)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createUsingDefault(ValueInstantiator.java:189)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:267)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createDefaultInstance(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3436)
	at com.webauthn4j.converter.util.JsonConverter.readValue(JsonConverter.java:53)
	... 15 common frames omitted

**To Reproduce**
`assertFalse(new FidoMdsMetadataItemsProvider(new ObjectConverter(), token).provide().isEmpty());`

will fail and warnings like the one above will be written to the log.
This happens with the latest release and the current SNAPSHOT.

**Comment by ChristophKaser** [comment]
Nevermind, I figured it out. If anyone stumbles over the same issue: The problem was the ObjectConverter, which needs to be initialized like this:
```
ObjectMapper jsonMapper = new ObjectMapper();
jsonMapper.registerModule(new WebAuthnMetadataJSONModule()); // This is the crucial part
ObjectMapper cborMapper = new ObjectMapper(new CBORFactory());
ObjectConverter objectConverter = new ObjectConverter(jsonMapper, cborMapper);
```
