### ISSUE TITLE
JSON serialization problems with Authenticator data

### ISSUE THREAD

**Issue by adam-siklosi** [webauthn4j/webauthn4j#589]
**Describe the bug**
According to the discussion in https://github.com/webauthn4j/webauthn4j/discussions/447 we should be able to save an Authenticator object using Jackson converters provided by webautn4j.

The serialization part seem to run fine, however deserializing the serialized data doesn't work.
In my opinion the examples below show that there is actually a problem with the result of the JSON serialization.

**To Reproduce**
1.) Deserialization of AAGUID
```
@Test
public void mapAauid() {
     JsonConverter converter = new ObjectConverter().getJsonConverter();
     String asString = converter.writeValueAsString(AAGUID.ZERO);
     converter.readValue(asString, AAGUID.class);
}
```
Causes the following exception. Seems like the problem is that somehow we get both the byte and UUID value serialized to JSON.
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.webauthn4j.data.attestation.authenticator.AAGUID` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"value":"00000000-0000-0000-0000-000000000000","bytes":"AAAAAAAAAAAAAAAAAAAAAA=="}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at com.webauthn4j.converter.util.JsonConverter.readValue(JsonConverter.java:54)
	... 52 more
```

2.) Deserialization of Attestations
```
    @Test
    public void mapNoneAttestation() {
        JsonConverter converter = new ObjectConverter().getJsonConverter();
        String asString = converter.writeValueAsString(new NoneAttestationStatement());
        converter.readValue(asString, AttestationStatement.class);
    }
```
or

```
    @Test
    public void mapPackedAttestation() {
        JsonConverter converter = new ObjectConverter().getJsonConverter();
        String asString = converter.writeValueAsString(
                new PackedAttestationStatement(
                        COSEAlgorithmIdentifier.RS1,
                        new byte[]{1},
                        null
                ));
        converter.readValue(asString, AttestationStatement.class);
    }
```

Causes an exception. See example below for the packed attestation case. Seems like the problem is that the type information is not serialized to JSON therefore Jackson doesn't know which implementation of the interface should be instantiated. (note: in the test I could easily use an exact implementation class to avoid the error, however at runtime the system will not know which implementation to use)
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.webauthn4j.data.attestation.statement.AttestationStatement` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"alg":-65535,"sig":"AQ=="}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1764)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1209)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:274)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at com.webauthn4j.converter.util.JsonConverter.readValue(JsonConverter.java:54)
```

In my opinion this is caused by the ignore property setting on the attestation classes, not sure what was the purpose of that.
```
@JsonIgnoreProperties(value = "format")
@JsonTypeName(PackedAttestationStatement.FORMAT)
```

**Expected behavior**
We should be able to deserialize serialized objects.

**Version information:**
 - OS: Fedora 34 or CentOs 7.7.1908
 - Java: 1.8.0_302 or 1.8.0_282
 - Webauthn4j version: 0.17.2.RELEASE
 - Jackson version: 2.12.5

**Comment by ynojima** [comment]
Move Custom Serializers and Deserializers to json or cbor package to clarify its serialization/desierialization capability
https://github.com/webauthn4j/webauthn4j/pull/593
