### ISSUE TITLE
TPM attestation ECC / ECDSA

### ISSUE THREAD

**Issue by Fabien38300** [webauthn4j/webauthn4j#729]
Hi,

Some TPM attestations are not validated with error : 

> com.webauthn4j.converter.exception.DataConversionException: Input data does not match expected form
[...]
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: input byte array contains surplus data
at [Source: (byte[])[4033 bytes]; byte offset: #4033]
at com.webauthn4j.converter.jackson.deserializer.cbor.TPMTPublicDeserializer.deserialize(TPMTPublicDeserializer.java:46) ~[webauthn4j-core-0.20.2.RELEASE.jar!/:na]
at com.webauthn4j.converter.jackson.deserializer.cbor.TPMTPublicDeserializer.deserialize(TPMTPublicDeserializer.java:34) ~[webauthn4j-core-0.20.2.RELEASE.jar!/:na]

In this case, the value 35 is not found in the TPMIAlgPublic enum and deserialization fails.
Does that mean that the TPM is trying to use TPM_ALG_ECC whereas the lib expect TPM_ALG_ECDSA or TPM_ALG_RSA and does not support TPM_ALG_ECC ?

**Comment by ynojima** [comment]
Thank you for pointing that out.
I haven't expected to receive `TPM_ALG_ECC`, but it seems it needs to add `TPM_ALG_ECC` support.

**Comment by ynojima** [comment]
Fixed in https://github.com/webauthn4j/webauthn4j/pull/739
