### ISSUE TITLE
Upgrading from 0.19.1.RELEASE to 0.21.1.RELEASE causes deserialization error

### ISSUE THREAD

**Issue by ranjoy001** [webauthn4j/webauthn4j#844]
When upgrading from 0.19.1.RELEASE to 0.21.1.RELEASE, when attempting to deserialize the authenticator data we get:

Caused by: java.io.InvalidClassException: com.webauthn4j.data.attestation.statement.COSEAlgorithmIdentifier; local class incompatible: stream classdesc serialVersionUID = -2522347661776965556, local class serialVersionUID = -5339677057626639336
at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689) ~[?:?]
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2014) ~[?:?]
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1864) ~[?:?]
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2195) ~[?:?]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681) ~[?:?]
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490) ~[?:?]
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384) ~[?:?]
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222) ~[?:?]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681) ~[?:?]
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490) ~[?:?]
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384) ~[?:?]
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222) ~[?:?]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681) ~[?:?]
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490) ~[?:?]
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384) ~[?:?]
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222) ~[?:?]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681) ~[?:?]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:493) ~[?:?]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:451) ~[?:?]
at java.util.ArrayList.readObject(ArrayList.java:929) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175) ~[?:?]
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2351) ~[?:?]
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222) ~[?:?]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681) ~[?:?]
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490) ~[?:?]
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384) ~[?:?]
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222) ~[?:?]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681) ~[?:?]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:493) ~[?:?]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:451) ~[?:?]
at com.tremolosecurity.proxy.auth.webauthn.WebAuthnUtils.lookupWebAuthnUserData(WebAuthnUtils.java:134) ~[unison-server-core-1.0.31.jar:?]

To Reproduce

- create and serialize an authenticator object with 0.19.1.RELEASE
- deserialize with 0.21.1.RELEASE

Expected behavior

- deserialization should still work and be backwards compatible

Screenshots
N/A

Desktop (please complete the following information):
N/A

Smartphone (please complete the following information):
Iphone 14

**Comment by ynojima** [comment]
As webauthn4j data classes doesn't have serialVersionUID, they don't assures compatibility between versions. Please serialize and deserialize data with `CborConverter` or other utility classes offered by WebAuthn4j.
https://webauthn4j.github.io/webauthn4j/en/#authenticator-serialization-and-deserialization

**Comment by ranjoy001** [comment]
@ynojima apologies for catching up late on this, so right now we are using `apache-lang3` 's `SerializationUtils` class for serialisation and deserialisation of all these 3 fields(authenticator extension/ attestation statement/ attested credential data), so should we switch to using webauthn4j utility classes for this?

**Comment by ynojima** [comment]
Yes. 
Sorry for misleading Serializable interface.

**Comment by ranjoy001** [comment]
But still, webauthn4j data classes does not have serialVersionUID so they don't assure compatibility between different version of classes? one more thing  after going through this guide - https://webauthn4j.github.io/webauthn4j/en/#authenticator-serialization-and-deserialization, I found that webauthn4j provides different classes for serialising and deserialising these 3 fields(authenticator extension/ attestation statement/ attested credential data), so is it required to use different classes only or we can use the `CborConverter` only for all 3 fields.

**Comment by ynojima** [comment]
As long as you use JsonConverter or CborConverter, WebAuthn4J's data classes are designed to allow you to deserialize data that was serialized in previous versions.

**Comment by ynojima** [comment]
The misleading `Serializable` is removed from `0.23.0.RELEASE`
https://github.com/webauthn4j/webauthn4j/issues/845
