### ISSUE TITLE
Serializing attestation object throws exception

### ISSUE THREAD

**Issue by svartkanin** [webauthn4j/webauthn4j#899]
**Describe the bug**
I'm trying to serialize the whole attestation object as a JSON but that results in the below exception

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: class com.fasterxml.jackson.databind.ser.BeanPropertyWriter cannot access class sun.security.x509.X509CertImpl (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @68b32e3e (through reference chain: com.webauthn4j.data.attestation.AttestationObject["attStmt"]->com.webauthn4j.data.attestation.statement.PackedAttestationStatement["x5c"]->com.webauthn4j.data.attestation.statement.AttestationCertificatePath[0]->sun.security.x509.X509CertImpl["info"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:778)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4799)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4040)

```

**To Reproduce**
```
      val attestationObject: AttestationObject = registrationData.attestationObject
      JacksonObjectMapper.mapper.writeValueAsString(attestationObject)
```

**Expected behavior**
The jackson `writeValueAsString` should return a Json value

**Comment by ynojima** [comment]
To serialize `AttestationObject` into String, please use `AttestationObjectConverter#convertToBase64urlString`. It emits Base64Url encoded CBOR byte array.

**Comment by svartkanin** [comment]
But that is an encoded string, I would like to output a Json of the decoded data

**Comment by svartkanin** [comment]
Alright thanks
